; Custom PHP configuration
upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 256M
max_execution_time = 300
variables_order = "EGPCS"

; Secure Session Cookies (Recommended to only enable in production)
; session.cookie_httponly = 1
; session.cookie_secure = 1
; session.cookie_samesite = "Lax"
; session.use_strict_mode = 1